version: 2

models:
  - name: top_10_artists_soundcloud
    description: top 10 artists from soundcloud
    columns:
      - name: artists
        # tests:
        #   - not_null
      - name: count_artists
        # tests:
        #   - not_null
  - name: top_10_artists_spotify
    description: top 10 artists from spotify
    columns:
      - name: artists
        # tests:
        #   - not_null
      - name: count_artists
        # tests:
        #   - not_null
