jordans_music:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: jordans-music-343121
      dataset: music
      threads: 1
      keyfile: 'C:\python_personal\jordans-music\util\cred\jordans-cred.json'
      location: US
